# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, dym_word: str=None, dym_done: bool=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param dym_word: The dym_word of this InlineResponse200.  # noqa: E501
        :type dym_word: str
        :param dym_done: The dym_done of this InlineResponse200.  # noqa: E501
        :type dym_done: bool
        """
        self.swagger_types = {
            'dym_word': str,
            'dym_done': bool
        }

        self.attribute_map = {
            'dym_word': 'dym-word',
            'dym_done': 'dym-done'
        }

        self._dym_word = dym_word
        self._dym_done = dym_done

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dym_word(self) -> str:
        """Gets the dym_word of this InlineResponse200.

        payload after doing Did you mean on it  # noqa: E501

        :return: The dym_word of this InlineResponse200.
        :rtype: str
        """
        return self._dym_word

    @dym_word.setter
    def dym_word(self, dym_word: str):
        """Sets the dym_word of this InlineResponse200.

        payload after doing Did you mean on it  # noqa: E501

        :param dym_word: The dym_word of this InlineResponse200.
        :type dym_word: str
        """

        self._dym_word = dym_word

    @property
    def dym_done(self) -> bool:
        """Gets the dym_done of this InlineResponse200.

        wheather payload changed or not  # noqa: E501

        :return: The dym_done of this InlineResponse200.
        :rtype: bool
        """
        return self._dym_done

    @dym_done.setter
    def dym_done(self, dym_done: bool):
        """Sets the dym_done of this InlineResponse200.

        wheather payload changed or not  # noqa: E501

        :param dym_done: The dym_done of this InlineResponse200.
        :type dym_done: bool
        """

        self._dym_done = dym_done
